(define (sum-of-squares a b) (+ (* a a) (* b b)))
      
(define (ex1_3 a b c) 
  (if (> a b)
      ( if (> b c)
           (sum-of-squares a b)
           (sum-of-squares a c)
       )
      ( if (> a c)
           (sum-of-squares a b)
           (sum-of-squares c b)
       )
      )
  )

(ex1_3 1 2 3)
(ex1_3 2 1 3)
(ex1_3 3 2 1)
(ex1_3 1 3 2)
(ex1_3 2 3 1)
(ex1_3 3 2 1)